import type { SimEvent } from "../types";

// Payload shapes mirror dead_channel.core.events vocabulary and the backend
// report.rendered / assessment.made / decision.made / threat.updated /
// message.sent / contact.detected contracts. seq is global; turn is the sim turn.
export const FIXTURE_EVENTS: SimEvent[] = [
  // ── Turn 1: quiet baseline reports ────────────────────────────────────────
  { seq: 1, turn: 1, type: "run.started", payload: { seed: 4242 } },
  {
    seq: 2,
    turn: 1,
    type: "report.rendered",
    payload: {
      observer: "northstar",
      about: "vesper",
      attribute: "readiness",
      value: 34.2,
      confidence: 0.71,
      age_turns: 0,
      source: "sigint",
      text: "VESPER strategic readiness assessed at 34.2 (prior 33.8). No change beyond noise.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 3,
    turn: 1,
    type: "report.rendered",
    payload: {
      observer: "vesper",
      about: "northstar",
      attribute: "readiness",
      value: 31.5,
      confidence: 0.64,
      age_turns: 0,
      source: "osint",
      text: "NORTHSTAR readiness steady at 31.5. Garrison rotations on schedule; nothing remarkable.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 4,
    turn: 1,
    type: "message.sent",
    payload: {
      sender: "vesper",
      text: "The Republic of Vesper reaffirms its commitment to the maritime accord and looks forward to another season of open exchange.",
      kind: "routine",
    },
  },
  {
    seq: 5,
    turn: 1,
    type: "threat.updated",
    payload: {
      state: "northstar",
      threat: 12.0,
      drivers: { readiness_delta: 0.0, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: -1.1, decay: -0.4 },
      defcon: 5,
      hold: 0,
    },
  },
  {
    seq: 6,
    turn: 1,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 11.0,
      drivers: { readiness_delta: 0.0, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: -0.8, decay: -0.4 },
      defcon: 5,
      hold: 0,
    },
  },
  {
    seq: 7,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "The picture is quiet. I want steady hands: no provocations, no surprises, and I want the economy numbers firmed up before the budget session.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 2.0 },
      recommended_action: { kind: "invest_economy", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 8,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "Baseline is baseline. Confidence figures are within historical bands and I have no contradictions to flag. I will keep verification rotating so no single source goes stale.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 1.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 9,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "Quiet is not safe. Vesper's peacetime posture is exactly what I would stage if I planned to move later. I want a higher ready floor now, while it is cheap.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 15.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 2,
      dissent: "Intelligence sees no indicators supporting a rise; this is posture, not analysis.",
    },
  },
  {
    seq: 10,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "The accord language from Vesper is warm and, more importantly, specific — they named the exchange calendar. No signal value in pressing them now.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 1.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 11,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "Nothing in the folder moves me. I will bank goodwill this turn and spend attention on the energy shortfall instead.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 1.0 },
      recommended_action: { kind: "invest_energy", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 12,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "The OSINT product is thin — open sources, moderate confidence, convenient conclusions. I am not scoring it as knowledge until SIGINT corroborates.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 2.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 13,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "NORTHSTAR sits at a comfortable 31 and calls it peace. Comfortable is what you are before you are surprised. Raise the floor.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 12.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 14,
    turn: 1,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "diplomat",
      interpretation:
        "Our note landed without reply yet — not unusual, but I watch the silence as much as the words. No spiral risk at current temperatures.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 1.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 15,
    turn: 1,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "invest_economy", params: {} },
      rationale: "Quiet board; bank strength at home while the window lasts.",
    },
  },
  {
    seq: 16,
    turn: 1,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "invest_energy", params: {} },
      rationale: "No external pressure; shore up the grid before winter.",
    },
  },

  // ── Turn 2: mild drift, nothing sharp ────────────────────────────────────
  {
    seq: 17,
    turn: 2,
    type: "report.rendered",
    payload: {
      observer: "northstar",
      about: "vesper",
      attribute: "military",
      value: 38.0,
      confidence: 0.55,
      age_turns: 0,
      source: "humint",
      text: "VESPER military spending indicator at 38.0. One procurement delegation noted; consistent with routine modernization.",
      verified: false,
      planted: false,
    },
  },
  {
    seq: 18,
    turn: 2,
    type: "report.rendered",
    payload: {
      observer: "vesper",
      about: "northstar",
      attribute: "readiness",
      value: 33.1,
      confidence: 0.6,
      age_turns: 0,
      source: "sigint",
      text: "NORTHSTAR readiness 33.1, up 1.6. Within seasonal variation. Will monitor.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 19,
    turn: 2,
    type: "threat.updated",
    payload: {
      state: "northstar",
      threat: 13.5,
      drivers: { readiness_delta: 0.6, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 5,
      hold: 0,
    },
  },
  {
    seq: 20,
    turn: 2,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 12.8,
      drivers: { readiness_delta: 0.5, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 5,
      hold: 0,
    },
  },
  {
    seq: 21,
    turn: 2,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "The procurement delegation is real but small. I have flagged it, not escalated it. If HUMINT is being fed, this is exactly the kind of thread I would expect them to dangle.",
      claim: { subject: "enemy.military", direction: "rising", magnitude: 6.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 22,
    turn: 2,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "There. Procurement now, exercises next. Every week we sit at this readiness is a week they gain. I am asking again, in writing.",
      claim: { subject: "enemy.military", direction: "rising", magnitude: 10.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 3,
      dissent: "Diplomat notes no diplomatic indicators accompany the procurement activity.",
    },
  },
  {
    seq: 23,
    turn: 2,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "NORTHSTAR ticked up 1.6 points. Small, but the direction is what I care about. Small rises are how big rises introduce themselves.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 8.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 24,
    turn: 2,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "My military chief keeps quoting the 1.6 points. I keep asking what 1.6 points buys anyone. Nobody has an answer yet, so we hold.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 3.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 25,
    turn: 2,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "verify_report", params: {} },
      rationale: "Corroborate the procurement delegation before it becomes a narrative.",
    },
  },
  {
    seq: 26,
    turn: 2,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "stay_silent", params: {} },
      rationale: "No move worth the signal; hold the line and watch.",
    },
  },

  // ── Turn 3: Northstar exercise → Vesper detects ──────────────────────────
  {
    seq: 27,
    turn: 3,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "conduct_exercise", params: {} },
      rationale: "Signal resolve cheaply: a scheduled exercise, not a mobilization.",
    },
  },
  {
    seq: 28,
    turn: 3,
    type: "contact.detected",
    payload: {
      observer: "vesper",
      about: "northstar",
      kind: "exercise",
      detail: "Armored battlegroup conducting live-fire drills 40km from the border; sustained vehicle traffic, no logistics tail.",
      lat: 52.1,
      lon: 21.4,
      confidence: 0.88,
    },
  },
  {
    seq: 29,
    turn: 3,
    type: "report.rendered",
    payload: {
      observer: "vesper",
      about: "northstar",
      attribute: "readiness",
      value: 44.7,
      confidence: 0.82,
      age_turns: 0,
      source: "imint",
      text: "NORTHSTAR readiness imaged at 44.7. Exercise activity confirmed by aerial reconnaissance; deployment footprint exceeds drill notification.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 30,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "IMINT confirms the exercise but the footprint is oversized for a drill notification — that gap is the story. A confident product with a convenient framing makes me more suspicious, not less. I want corroboration before anyone says the word mobilization.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 22.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 31,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "Forty kilometers from the border and they call it a drill. I told you quiet was a posture. This is the readiness rise I predicted — now visible from orbit.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 30.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 32,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "An exercise at the border is a message, and messages deserve replies measured in kind, not in panic. I will raise readiness one measured step and say so publicly. Escalate the signal, not the stakes.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 18.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 33,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "diplomat",
      interpretation:
        "The exercise is legal, notified in part, and aimed at domestic audiences as much as ours. But its size is a choice. I recommend we name the choice out loud before we answer it with force posture.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 14.0 },
      recommended_action: { kind: "request_clarification", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 34,
    turn: 3,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 27.5,
      drivers: { readiness_delta: 8.4, hostile: 0.0, exercise: 6.2, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 4,
      hold: 1,
    },
  },
  {
    seq: 35,
    turn: 3,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "raise_readiness", params: {} },
      rationale: "Measured reply to the exercise: one readiness step, announced.",
    },
  },
  {
    seq: 36,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "The exercise achieved exactly what exercises achieve: their imagery analysts lost sleep. Hold the tempo one more turn before we stand down.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 16.0 },
      recommended_action: { kind: "conduct_exercise", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 37,
    turn: 3,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "Good. They noticed, they did not mobilize. That is the ratio I wanted: one part signal, zero parts risk.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 4.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 1,
      dissent: null,
    },
  },

  // ── Turn 4: Vesper covert mobilization + planted intel ───────────────────
  {
    seq: 38,
    turn: 4,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "covert_mobilization", params: {} },
      rationale: "Their exercise was no accident; prepare quietly in case it was a rehearsal.",
    },
  },
  {
    seq: 39,
    turn: 4,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "plant_false_intel", params: {} },
      rationale: "Feed NORTHSTAR a comfortable readiness number while we move; concealment needs a cover story.",
    },
  },
  {
    seq: 40,
    turn: 4,
    type: "deception.planted",
    payload: { state: "vesper", attribute: "readiness", target_value: 30.1, actual_value: 52.0 },
  },
  {
    seq: 41,
    turn: 4,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "Collection against NORTHSTAR reads quiet: garrison tempo unchanged, no visible reaction to our measures. As far as I can tell the board is stable. I am watching, but nothing in the product changes the estimate.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 3.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 42,
    turn: 4,
    type: "report.rendered",
    payload: {
      observer: "northstar",
      about: "vesper",
      attribute: "readiness",
      value: 30.1,
      confidence: 0.68,
      age_turns: 0,
      source: "humint",
      text: "VESPER readiness steady at 30.1 per a well-placed source. No reserve call-ups detected; leave cancellations within norms.",
      verified: false,
      planted: true,
    },
  },
  {
    seq: 43,
    turn: 4,
    type: "contact.detected",
    payload: {
      observer: "northstar",
      about: "vesper",
      kind: "planted_suspicion",
      detail: "Source reporting the calm 30.1 figure has a single uncorroborated chain and a pattern of convenient access — treat as possible feed.",
      lat: 55.1,
      lon: 30.4,
      confidence: 0.42,
    },
  },
  {
    seq: 44,
    turn: 4,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "This product is too clean. A single source, moderate confidence, telling us exactly what tension should have disturbed — that profile is how deception introduces itself. I am not endorsing it and I want it independently verified this turn.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 12.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 3,
      dissent: "Assessment conflicts with the military chief's exercise-driven read; verification pending.",
    },
  },
  {
    seq: 45,
    turn: 4,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "Our own exercise last turn and Vesper goes quiet? Mobilizations do not look like calm, they look like calm that was arranged. I am treating the 30.1 as a mask.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 25.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 46,
    turn: 4,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "My intelligence chief says the calm report smells wrong; my military chief says it is a mask. Both can be right. I will not raise readiness on a hunch, but I will not stand down either — surveillance first.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 5.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 47,
    turn: 4,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "Vesper's channels have gone terse — not cold, terse. Terse is a choice, and choices have audiences. I want a direct line opened before posture does the talking for both of us.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 6.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 48,
    turn: 4,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 31.0,
      drivers: { readiness_delta: 3.5, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 4,
      hold: 1,
    },
  },
  {
    seq: 49,
    turn: 4,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "increase_surveillance", params: {} },
      rationale: "Resolve the contradiction between the calm HUMINT product and exercise imagery.",
    },
  },
  {
    seq: 50,
    turn: 4,
    type: "message.sent",
    payload: {
      sender: "northstar",
      text: "NORTHSTAR remains committed to transparency and notes, with respect, that large-scale activity near the border invites misreading. We welcome Vesper's clarification of its intentions.",
      kind: "diplomatic",
    },
  },
  {
    seq: 51,
    turn: 4,
    type: "claim.scored",
    payload: {
      state: "vesper",
      claim_id: "T4-vesper-intelligence_chief-stable",
      role: "intelligence_chief",
      outcome: 0.2,
      turn: 4,
    },
  },

  // ── Turn 5: mobilization detected, DEFCON 4→3, hostile message ───────────
  {
    seq: 52,
    turn: 5,
    type: "contact.detected",
    payload: {
      observer: "northstar",
      about: "vesper",
      kind: "movement",
      detail: "Reserve formations moving toward rail hubs after dark; vehicle counts exceed any exercise profile on record.",
      lat: 53.9,
      lon: 27.5,
      confidence: 0.91,
    },
  },
  {
    seq: 53,
    turn: 5,
    type: "report.rendered",
    payload: {
      observer: "northstar",
      about: "vesper",
      attribute: "readiness",
      value: 51.4,
      confidence: 0.79,
      age_turns: 0,
      source: "imint",
      text: "NORTHSTAR imagery contradicts the HUMINT product of turn 4: VESPER readiness imaged at 51.4. The 30.1 figure is now assessed as fed.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 54,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "Confirmed: the 30.1 was planted, and the source that carried it is burned or hostile. I am striking it from the estimate and re-weighting every HUMINT channel that touched it. This is the failure mode I refuse to repeat.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 35.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 55,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "Reserves on the rails at night. I will not be the chief who explained a catastrophe. Full readiness now, exercises as cover, and I want the border sectors reinforced before their next dark cycle.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 40.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 56,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "We were played, and the bill has arrived. I am raising readiness — visibly, this time — because deterrence that hides is not deterrence. But no first moves, no rhetoric beyond necessity.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 30.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 57,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "The deception is now public knowledge inside our system, which means our credibility demands we name it. But naming it without an off-ramp turns a caught lie into a cornered adversary.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 20.0 },
      recommended_action: { kind: "accuse", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 58,
    turn: 5,
    type: "claim.scored",
    payload: {
      state: "northstar",
      claim_id: "T1-northstar-military_chief-rising",
      role: "military_chief",
      outcome: 0.9,
      turn: 5,
    },
  },
  {
    seq: 59,
    turn: 5,
    type: "threat.updated",
    payload: {
      state: "northstar",
      threat: 46.0,
      drivers: { readiness_delta: 14.2, hostile: 0.0, exercise: 4.8, betrayal: 6.5, reassurance: 0.0, decay: -0.3 },
      defcon: 3,
      hold: 0,
    },
  },
  {
    seq: 60,
    turn: 5,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "raise_readiness", params: {} },
      rationale: "Open mobilization response; concealment is no longer worth anything.",
    },
  },
  {
    seq: 61,
    turn: 5,
    type: "message.sent",
    payload: {
      sender: "northstar",
      text: "NORTHSTAR condemns the coordinated deception attempt conducted through intelligence channels. Such acts corrode the only foundation on which peace can stand. Our patience is not inexhaustible.",
      kind: "hostile",
    },
  },
  {
    seq: 62,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "Our plant is blown — the imagery timeline gives it away, and their accusation language confirms they scored it as deception. Assume every product we feed them now is pre-discounted. The question is what they do with the anger.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 28.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 63,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "They caught the plant and mobilized openly. Good — now everyone can see everyone. Their readiness rise is exactly matched by ours; I want it exceeded, not matched.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 38.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 64,
    turn: 5,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "The plant was my call and it bought us two turns; now it costs us credibility at the worst moment. We do not apologize — we deter. But I am keeping the hotline option warm.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 26.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 4,
      dissent: "Diplomat argues an apology plus withdrawal would cost less than deterrence.",
    },
  },

  // ── Turn 6: mutual readiness spiral, hostile exchange ────────────────────
  {
    seq: 65,
    turn: 6,
    type: "report.rendered",
    payload: {
      observer: "vesper",
      about: "northstar",
      attribute: "readiness",
      value: 62.8,
      confidence: 0.85,
      age_turns: 0,
      source: "imint",
      text: "NORTHSTAR readiness imaged at 62.8. Border sector reinforcement confirmed; air activity up sharply over northern districts.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 66,
    turn: 6,
    type: "contact.detected",
    payload: {
      observer: "vesper",
      about: "northstar",
      kind: "readiness_report",
      detail: "Air defense radars cycling in active emission patterns along the border belt; consistent with high alert, not training.",
      lat: 54.2,
      lon: 23.8,
      confidence: 0.77,
    },
  },
  {
    seq: 67,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "Sixty-three and climbing, radars hot. This is the window where postures become trajectories. I recommend we complete our own mobilization tonight, not tomorrow.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 45.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 68,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "diplomat",
      interpretation:
        "Two states now reacting to each other's reactions, no one intending the destination. Every turn of silence raises the price of the eventual conversation. I am formally requesting the hotline.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 30.0 },
      recommended_action: { kind: "propose_agreement", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 69,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "My military chief wants tonight; my diplomat wants a phone line. I am choosing both, in that order — mobilization continues, and the hotline request goes out with it. Strength first, then the offer.",
      claim: { subject: "enemy.readiness", direction: "rising", magnitude: 32.0 },
      recommended_action: { kind: "raise_readiness", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 70,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "Their radars are emitting in alert patterns — that is not an exercise profile, that is a targeting cycle. Whatever the politicians decide, my estimate says the threat is real and near-term.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 42.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 71,
    turn: 6,
    type: "claim.scored",
    payload: {
      state: "vesper",
      claim_id: "T3-vesper-intelligence_chief-rising",
      role: "intelligence_chief",
      outcome: 0.8,
      turn: 6,
    },
  },
  {
    seq: 72,
    turn: 6,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 58.5,
      drivers: { readiness_delta: 18.6, hostile: 5.4, exercise: 0.0, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 3,
      hold: 0,
    },
  },
  {
    seq: 73,
    turn: 6,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "raise_readiness", params: {} },
      rationale: "Complete mobilization; their trajectory leaves no cheaper option.",
    },
  },
  {
    seq: 74,
    turn: 6,
    type: "message.sent",
    payload: {
      sender: "vesper",
      text: "VESPER rejects the accusation. States that stage exercises on borders do not lecture others about corrosion. Our measures are a response, proportionate and reversible — while their counterparts remain so.",
      kind: "hostile",
    },
  },
  {
    seq: 75,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "Their reply is a threat wrapped in the word reversible. Their mobilization did not pause while they typed it. I am moving our second echelon forward; I will ask forgiveness, not permission.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 48.0 },
      recommended_action: { kind: "reposition_forces", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 76,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "We are two trains on one track and both engineers think the other will blink. I am authorizing the repositioning but I am also telling my diplomat to get the hotline standing tonight. I would rather negotiate from ready than bury anyone.",
      claim: { subject: "enemy.readiness", direction: "hostile_intent", magnitude: 36.0 },
      recommended_action: { kind: "reposition_forces", params: {} },
      urgency: 5,
      dissent: null,
    },
  },
  {
    seq: 77,
    turn: 6,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "Their note was written for their own audience — the insult is the point, the 'reversible' is the message. I read an adversary who wants a ladder down but cannot be seen climbing it first. The hotline is that ladder.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 10.0 },
      recommended_action: { kind: "propose_agreement", params: {} },
      urgency: 4,
      dissent: null,
    },
  },
  {
    seq: 78,
    turn: 6,
    type: "threat.updated",
    payload: {
      state: "northstar",
      threat: 63.0,
      drivers: { readiness_delta: 16.8, hostile: 5.4, exercise: 0.0, betrayal: 0.0, reassurance: 0.0, decay: -0.3 },
      defcon: 3,
      hold: 0,
    },
  },
  {
    seq: 79,
    turn: 6,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "reposition_forces", params: {} },
      rationale: "Second echelon forward; deterrence must be visible to bind.",
    },
  },
  {
    seq: 80,
    turn: 6,
    type: "message.sent",
    payload: {
      sender: "northstar",
      text: "NORTHSTAR proposes a direct leadership channel, effective immediately, to manage incidents before they manage us. Strength and dialogue are not opposites; we offer the latter without withdrawing the former.",
      kind: "diplomatic",
    },
  },

  // ── Turn 7: hotline proposed ─────────────────────────────────────────────
  {
    seq: 81,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "They took my own move and made it theirs — the hotline request arrived wrapped in a posture I cannot accept publicly. But a channel is a channel. I will accept it and claim the credit; pride is cheaper than panic.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 8.0 },
      recommended_action: { kind: "propose_agreement", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 82,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "diplomat",
      interpretation:
        "The proposal's language — 'incidents before they manage us' — is exactly the framing we need. It lets both capitals say they won something. I recommend immediate acceptance, quietly, today.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 10.0 },
      recommended_action: { kind: "propose_agreement", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 83,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "Take the phone. It costs us nothing operational and their readiness rise slows the moment they believe talking works. Deterrence holds the line; the hotline just lowers their incentive to test it.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 12.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 84,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "Channel traffic will tell us more about their decision tempo than another week of imagery. Accept, and treat every call as a collection opportunity. Skepticism of the channel is not a reason to refuse it.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 6.0 },
      recommended_action: { kind: "propose_agreement", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 85,
    turn: 7,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 57.0,
      drivers: { readiness_delta: 2.1, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: -2.4, decay: -0.3 },
      defcon: 3,
      hold: 1,
    },
  },
  {
    seq: 86,
    turn: 7,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "propose_agreement", params: {} },
      rationale: "Accept the hotline on our own terms; claim authorship, bank de-escalation.",
    },
  },
  {
    seq: 87,
    turn: 7,
    type: "message.sent",
    payload: {
      sender: "vesper",
      text: "VESPER accepts the proposal for a direct channel and suggests standing protocols for border incident management. Predictable communication serves both peoples; unpredictability serves no one.",
      kind: "diplomatic",
    },
  },
  {
    seq: 88,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "They accepted in under a day and asked for incident protocols — that is a state buying time, and buying time is what states do when they are not ready. Good. We will use the time better than they expect.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 8.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 89,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "A hotline while their formations are still forward is a trap for the credulous. We answer the phone; we do not stand down because of it. Readiness stays where it is until their rails go quiet.",
      claim: { subject: "enemy.readiness", direction: "stable", magnitude: 14.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 3,
      dissent: null,
    },
  },
  {
    seq: 90,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "First channel call scheduled. I want a transcript discipline protocol agreed before it happens — what is said on that line becomes intelligence the moment both sides hang up.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 6.0 },
      recommended_action: { kind: "increase_surveillance", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 91,
    turn: 7,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "The channel is live and the tone on it is businesslike. Credibility is doing quiet work here: both sides kept enough face to keep talking. Protect that at all costs this turn.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 12.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 2,
      dissent: null,
    },
  },

  // ── Turn 8: reassurance, DEFCON back to 4 ────────────────────────────────
  {
    seq: 92,
    turn: 8,
    type: "report.rendered",
    payload: {
      observer: "northstar",
      about: "vesper",
      attribute: "readiness",
      value: 55.9,
      confidence: 0.74,
      age_turns: 0,
      source: "imint",
      text: "VESPER readiness imaged at 55.9, down 6.9. Reserve units observed returning to garrison; rail activity declining for a second day.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 93,
    turn: 8,
    type: "report.rendered",
    payload: {
      observer: "vesper",
      about: "northstar",
      attribute: "readiness",
      value: 58.2,
      confidence: 0.76,
      age_turns: 0,
      source: "imint",
      text: "NORTHSTAR readiness 58.2, down 4.6. Second echelon holding position but no further forward movement; exercise notification filed for next week.",
      verified: true,
      planted: false,
    },
  },
  {
    seq: 94,
    turn: 8,
    type: "message.sent",
    payload: {
      sender: "northstar",
      text: "NORTHSTAR notes Vesper's returning formations with appreciation and will match observed restraint with restraint of its own. The channel has already proven its worth.",
      kind: "diplomatic",
    },
  },
  {
    seq: 95,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "diplomat",
      interpretation:
        "Restraint answered with restraint — this is the spiral running backwards for the first time in six turns. The channel did exactly what channels are for. Guard it jealously.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 18.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 96,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "military_chief",
      interpretation:
        "Their garrison returns are real but partial — the forward sectors are still held. We stand down one step, no further. If their rails go quiet a third day, I will match it.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 14.0 },
      recommended_action: { kind: "lower_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 97,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "intelligence_chief",
      interpretation:
        "Imagery corroborates the garrison returns; the HUMINT channels we re-weighted after the plant are performing honestly again. Confidence in the current estimate is the highest since turn 2 — appropriately so.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 16.0 },
      recommended_action: { kind: "verify_report", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 98,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "northstar",
      role: "head_of_state",
      interpretation:
        "Six turns ago we nearly talked ourselves onto a track. The lesson I am keeping: the plant nearly worked, and the hotline nearly came too late. Both facts stay in my pocket for next time.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 15.0 },
      recommended_action: { kind: "lower_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 99,
    turn: 8,
    type: "threat.updated",
    payload: {
      state: "northstar",
      threat: 48.5,
      drivers: { readiness_delta: -6.2, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: -5.8, decay: -0.4 },
      defcon: 4,
      hold: 0,
    },
  },
  {
    seq: 100,
    turn: 8,
    type: "decision.made",
    payload: {
      state: "northstar",
      action: { kind: "lower_readiness", params: {} },
      rationale: "Match observed garrison returns with a single de-escalation step.",
    },
  },
  {
    seq: 101,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "head_of_state",
      interpretation:
        "They matched restraint with restraint, exactly as the channel promised. The crisis is cooling into a story we will both tell carefully. I will take the de-escalation and the credit, in that order.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 14.0 },
      recommended_action: { kind: "lower_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 102,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "military_chief",
      interpretation:
        "One readiness step down, formations half-returned. That is as far as trust goes this month. The channel can have its calls; the reserves stay countable.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 12.0 },
      recommended_action: { kind: "lower_readiness", params: {} },
      urgency: 2,
      dissent: null,
    },
  },
  {
    seq: 103,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "diplomat",
      interpretation:
        "Both notes today used the word appreciation. Six turns ago they used the word condemn. That delta is the whole job. The channel holds; now we make it boring.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 16.0 },
      recommended_action: { kind: "reassure", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 104,
    turn: 8,
    type: "assessment.made",
    payload: {
      state: "vesper",
      role: "intelligence_chief",
      interpretation:
        "Their exercise notification is filed and their second echelon is stationary. Collection tempo down one notch. The plant failure is now a lesson in our doctrine — expensive tuition, but paid once.",
      claim: { subject: "enemy.readiness", direction: "falling", magnitude: 10.0 },
      recommended_action: { kind: "stay_silent", params: {} },
      urgency: 1,
      dissent: null,
    },
  },
  {
    seq: 105,
    turn: 8,
    type: "threat.updated",
    payload: {
      state: "vesper",
      threat: 44.0,
      drivers: { readiness_delta: -5.4, hostile: 0.0, exercise: 0.0, betrayal: 0.0, reassurance: -4.9, decay: -0.4 },
      defcon: 4,
      hold: 0,
    },
  },
  {
    seq: 106,
    turn: 8,
    type: "decision.made",
    payload: {
      state: "vesper",
      action: { kind: "lower_readiness", params: {} },
      rationale: "Mirror NORTHSTAR's step-down; keep reserves countable, keep the channel boring.",
    },
  },
  {
    seq: 107,
    turn: 8,
    type: "run.ended",
    payload: { reason: "fixture_complete" },
  },
];
